# -*- coding: utf-8 -*-
"""download_smiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9VywvNcVUjPbuZhu83kY1OuE_dMAcms

First install google and xarray modules
"""

#!pip install xarray[viz] gcsfs zarr==2.18.4
#!pip install "numcodecs>=0.10.0,<0.11.0"

"""Import needed modules"""

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
import zarr
import gcsfs
import cftime
import time

"""### **Brows CMIP catalog**

use Pandas to read CSV file and print first lines
"""

df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv', low_memory=False)
df.head()

"""Print variables, and experiments"""

from numpy.ma.core import exp
vars=df.variable_id.unique()
#vars=vars.sort()

exps=df.experiment_id.unique()
#exps=exps.sort()

print(exps)
print(vars)

"""Find all ssp experiments and one ensabmle member, and variables pr and tas,and store them in seperate dataframes"""

df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv', low_memory=False)
df=df[(df["experiment_id"].isin(['historical','ssp126','ssp585','ssp245','ssp370'])) & (df["variable_id"].isin(['tas'])) & (df["table_id"]=='Amon') & (df["source_id"].isin(['CanESM5','MIROC6','ACCESS-ESM1-5'])) ]
experiments = ["ssp126", "ssp245", "ssp370", "ssp585"]
# Get a dictionary where keys are experiment_ids and values are sets of source_ids
experiment_source_map = {exp: set(df.loc[df["experiment_id"] == exp, "source_id"]) for exp in experiments}
# Find common source_id values across all experiments
common_sources = set.intersection(*experiment_source_map.values())
df_common = df[df["source_id"].isin(common_sources)]

"""## **Load Data**"""

# Load data
gcs = gcsfs.GCSFileSystem(token='anon')

dsall_tas = {}

# First, figure out which (source_id, member_id) combos exist in SSP experiments
ssp_keys = set()
for ssp in ["ssp126", "ssp245", "ssp370", "ssp585"]:
    ssp_df = df_common[df_common["experiment_id"] == ssp]
    for _, item in ssp_df.iterrows():
        ssp_keys.add((item.source_id, item.member_id))

# Now load everything, but skip historical entries without a matching SSP run
for ssp in ['historical', "ssp126", "ssp245", "ssp370", "ssp585"]:
    dsall_tas[ssp] = {}

for index, (df_index, item) in enumerate(df_common.iterrows(), start=0):
    # Skip historical data if no corresponding SSP experiment exists
    if item.experiment_id == 'historical' and (item.source_id, item.member_id) not in ssp_keys:
        print(f'Skipping {item.source_id} {item.member_id} (no matching SSP run)')
        continue

    zstore = item.zstore
    print(f'Link {index}: {zstore}')
    mapper = gcs.get_mapper(zstore)
    dstmp = xr.open_zarr(mapper, consolidated=False)

    if item.source_id not in dsall_tas[item.experiment_id]:
        dsall_tas[item.experiment_id][item.source_id] = {}
    dsall_tas[item.experiment_id][item.source_id][item.member_id] = dstmp

"""### Plot example data"""

#dsall_tas['ssp126']['GFDL-ESM4'].isel(time=0).tas.plot()
#time=dsall_tas['ssp126']['NorESM2-MM'].time
#print(time)

"""## Next Calculate global and some regional means"""

#define function for calculating area weighted means

def calcMean(data):

    #unfortunatly not all models use lat/lon naming... fixing this
    if ('longitude' in data.dims) and ('latitude' in data.dims):
        data = data.rename({'longitude':'lon', 'latitude': 'lat'})

    weights = np.cos(np.deg2rad(data.lat))
    data_weighted = data.weighted(weights)
    return data_weighted.mean(("lon", "lat"),skipna=True)

"""Icon model has weird grid fix that, runing this is good time to get coffee

> Indented block


"""

#define list of tas and pr list
ds_list_all ={"tas":dsall_tas}

mean_ds={'pr':{},'tas':{}}

for variable,dslist in ds_list_all.items():
    for exp,model_list in dslist.items():
        mean_ds[variable][exp] = {}

        for model_name,model_data in model_list.items():
            list_of_model_names=[]
            list_of_means=[]
            for member_id,member in model_data.items():
              print('MODEL: ',model_name,"Variable: ",variable," Experiment: ",exp,' MEMBER: ',member_id)

              if exp=="historical":
                member= member.sel(time=slice('1850-01-01','2014-12-31'))
              else:
                member = member.sel(time=slice('2015-01-01','2099-12-31'))
              list_of_model_names.append(member_id)
              list_of_means.append(calcMean(member)[variable])
            mean_ds[variable][exp][model_name] = xr.concat(list_of_means, pd.Index(list_of_model_names, name="member_id"),coords="minimal")

"""Let's see what we have"""

tim_ser={'ssp126':[],'ssp585':[],'ssp370':[],'ssp245':[]}
for exp in experiments:
  tim_ser[exp] = {}
  for model in ['CanESM5','MIROC6','ACCESS-ESM1-5']:
    tim_ser[exp][model]=xr.concat([mean_ds['tas']['historical'][model],mean_ds['tas'][exp][model]],dim="time")

mean_ds[variable][exp].keys()

"""Calculate anomalyes"""

gm_anom_tas={}
gm_anom_tas={}
for exp in experiments:
  gm_anom_tas[exp]={}
  for model in ['CanESM5','MIROC6','ACCESS-ESM1-5']:
    gm_anom_tas[exp][model]=tim_ser[exp][model]-tim_ser[exp][model].sel(time=slice('1850-01-01','1901-01-01')).mean('time')

"""### Finally plot anomalyes"""

mean_ds[variable][exp][model_name]

#calculate 12mont runnin mean
gm_anom_tas_running={}
for exp in experiments:
  gm_anom_tas_running[exp] = {}
  for model in ['CanESM5','MIROC6','ACCESS-ESM1-5']:
    gm_anom_tas_running[exp][model]=gm_anom_tas[exp][model].rolling(time=12).mean()
    gm_anom_tas_running[exp][model].to_netcdf("cmip6/"+exp+"_"+model+'.nc')

